import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const source = readFileSync(resolve(__dirname, '../components/AimdRecorderEditor.vue'), 'utf8')
const wysiwygSurfaceSource = readFileSync(resolve(__dirname, '../components/AimdRecorderWysiwygSurface.vue'), 'utf8')
const recorderMilkdownSource = readFileSync(resolve(__dirname, '../components/recorderMilkdownPlugin.ts'), 'utf8')
const componentExports = readFileSync(resolve(__dirname, '../components/index.ts'), 'utf8')
const rootExports = readFileSync(resolve(__dirname, '../index.ts'), 'utf8')

describe('AimdRecorderEditor', () => {
  it('combines the package editor and recorder around the same content and record models', () => {
    expect(source).toMatch(/import \{ AimdEditor \} from '@airalogy\/aimd-editor\/vue'/)
    expect(source).toMatch(/import AimdRecorder from '\.\/AimdRecorder\.vue'/)
    expect(source).toMatch(/const contentDraft = ref\(props\.content \|\| ''\)/)
    expect(source).toMatch(/const visualContentDraft = ref\(props\.content \|\| ''\)/)
    expect(source).toMatch(/const activeContentSurface = ref<'source' \| 'visual' \| null>\(null\)/)
    expect(source).toMatch(/const VISUAL_CONTENT_SYNC_DELAY_MS = 120/)
    expect(source).toMatch(/trackRecentSourceDraft\(value\)/)
    expect(source).toMatch(/recentVisualProgrammaticValues\.has\(value\)/)
    expect(source).toMatch(/recentSourceDraftValues\.has\(value\)/)
    expect(source).toMatch(/function handleEditorContentUpdate\(value: string\) \{\s*activeContentSurface\.value = 'source'/)
    expect(source).toMatch(/function handleVisualContentUpdate\(value: string\) \{/)
    expect(source).toMatch(/activeContentSurface\.value = 'visual'/)
    expect(source).toMatch(/function handleSourceSurfaceFocusIn\(\)/)
    expect(source).toMatch(/function handleVisualSurfaceFocusIn\(\)/)
    expect(source).toMatch(/function handleContentSurfaceFocusOut\(/)
    expect(source).toMatch(/scheduleVisualContentSync/)
    expect(source).toMatch(/function syncContentDraftFromProp\(value: string \| undefined\)/)
    expect(source).toMatch(/pendingContentEchoes: string\[\] = \[\]/)
    expect(source).toMatch(/emit\('update:modelValue', value\)/)
    expect(source).toMatch(/emit\('update:editorMode', \$event\)/)
    expect(source).toMatch(/<AimdEditor/)
    expect(source).toMatch(/<AimdRecorder/)
  })

  it('surfaces detached record values after protocol structure changes so users can migrate data into new fields', () => {
    expect(source).toMatch(/function collectDetachedRecordData\(/)
    expect(source).toMatch(/showDetachedData/)
    expect(source).toMatch(/hasDetachedData/)
    expect(source).toMatch(/detachedDataDescriptionLabel/)
    expect(source).toMatch(/detachedRecordJson/)
  })

  it('includes a structure editor for adding, deleting, retagging, and dragging recorder fields', () => {
    expect(source).toMatch(/showFieldStructure/)
    expect(source).toMatch(/showFieldStructure: false/)
    expect(source).toMatch(/scanWorkbenchFields/)
    expect(source).toMatch(/handleAddField/)
    expect(source).toMatch(/handleDeleteField/)
    expect(source).toMatch(/handleFieldKindCommit/)
    expect(source).toMatch(/handleFieldIdCommit/)
    expect(source).toMatch(/handleFieldDragStart/)
    expect(source).toMatch(/handleFieldDrop/)
    expect(source).toMatch(/aimd-recorder-workbench__field-list/)
    expect(source).toMatch(/draggable="!readonly"/)
  })

  it('keeps recorder-side helper panels in a tabbed workspace instead of only rendering them below the main layout', () => {
    expect(source).toMatch(/type WorkbenchSideTab = 'recorder' \| 'structure' \| 'record' \| 'detached'/)
    expect(source).toMatch(/const activeSideTab = ref<WorkbenchSideTab>\('recorder'\)/)
    expect(source).toMatch(/const sideTabs = computed\(\(\) =>/)
    expect(source).toMatch(/const sidePanelBodyStyle = computed\(\(\) => \(\{/)
    expect(source).toMatch(/aimd-recorder-workbench__side-tabs/)
    expect(source).toMatch(/aimd-recorder-workbench__side-tab--active/)
    expect(source).toMatch(/aimd-recorder-workbench__panel-body--recorder \{[\s\S]*overflow: auto;/)
  })

  it('can fit both columns to the remaining viewport height while still exposing a fixed-height opt-out', () => {
    expect(source).toMatch(/fitViewport\?: boolean/)
    expect(source).toMatch(/viewportOffset\?: number/)
    expect(source).toMatch(/fitViewport: true/)
    expect(source).toMatch(/viewportOffset: 24/)
    expect(source).toMatch(/function getViewportHeight\(\)/)
    expect(source).toMatch(/return window\.visualViewport\?\.height \?\? window\.innerHeight/)
    expect(source).toMatch(/function updateViewportPanelHeights\(/)
    expect(source).toMatch(/const viewportVisualEditorMinHeight = ref/)
    expect(source).toMatch(/const recorderToolbarHeight = getElementHeight\(recorderToolbarRef\.value\)/)
    expect(source).toMatch(/const visualEditorToolbarHeight = getElementHeight\(sidePanelBodyRef\.value\?\.querySelector\('\.aimd-editor-toolbar'\)\)/)
    expect(source).toMatch(/workbenchRef\.value\?\.getBoundingClientRect\(\)\.top/)
    expect(source).toMatch(/window\.addEventListener\('resize', scheduleViewportPanelHeights/)
  })

  it('supports recorder-side visual editing so field controls can be changed around live recorder widgets', () => {
    expect(source).toMatch(/visualEditMode/)
    expect(source).toMatch(/import AimdRecorderWysiwygSurface from '\.\/AimdRecorderWysiwygSurface\.vue'/)
    expect(source).toMatch(/renderVisualEditWrapper/)
    expect(source).toMatch(/renderVisualInsertEntry/)
    expect(source).toMatch(/showVisualEditToggle/)
    expect(source).toMatch(/initialVisualEditMode/)
    expect(source).toMatch(/activeFieldEditor/)
    expect(source).toMatch(/fieldEditorRawDraft/)
    expect(source).toMatch(/aimd-recorder-workbench__visual-toggle/)
    expect(source).toMatch(/aimd-recorder-workbench__panel-body--visual-editor/)
    expect(source).toMatch(/@edit-field="handleVisualFieldEdit"/)
    expect(source).toMatch(/@delete-field="handleVisualFieldDelete"/)
    expect(source).toMatch(/AimdRecorderWysiwygSurface/)
    expect(source).toMatch(/aimd-recorder-workbench__dialog/)
    expect(source).toMatch(/WYSIWYG AIMD editor|所见即所得编辑器/)
  })

  it('reuses base AIMD parsing while overriding recorder-editable node views with real recorder widgets', () => {
    expect(wysiwygSurfaceSource).not.toMatch(/aimdMilkdownPlugins/)
    expect(wysiwygSurfaceSource).toMatch(/\.\.\.createRecorderMilkdownPlugins\(/)
    expect(recorderMilkdownSource).toMatch(/aimdRemarkPlugin/)
    expect(recorderMilkdownSource).toMatch(/aimdFieldNode/)
    expect(recorderMilkdownSource).toMatch(/aimdFieldInputRule/)
    expect(recorderMilkdownSource).toMatch(/RECORDER_EDITABLE_INLINE_FIELD_TYPES = new Set\(\['var', 'var_table', 'step', 'check'\]\)/)
    expect(recorderMilkdownSource).toMatch(/RECORDER_QUIZ_MDAST_TYPE = 'aimdRecorderQuizBlock'/)
    expect(recorderMilkdownSource).toMatch(/dropCursor/)
    expect(recorderMilkdownSource).toMatch(/class: 'aimd-recorder-dropcursor'/)
    expect(recorderMilkdownSource).toMatch(/new RecorderWidgetNodeView\(node, view, getPos, options, false\)/)
    expect(recorderMilkdownSource).toMatch(/new AimdFieldChipNodeView\(node, view, getPos\)/)
    expect(recorderMilkdownSource).toMatch(/setAttribute\('data-drag-handle', 'true'\)/)
    expect(recorderMilkdownSource).toMatch(/if \(this\.dragHandleEl\?\.contains\(target\)\) \{\s*return false\s*\}/)
    expect(recorderMilkdownSource).toMatch(/state\.addNode\('code', undefined, String\(node\.attrs\.fieldContent \|\| ''\), \{ lang: 'quiz' \}\)/)
    expect(wysiwygSurfaceSource).toMatch(/--aimd-recorder-drop-label/)
    expect(wysiwygSurfaceSource).toMatch(/\.aimd-recorder-dropcursor/)
    expect(wysiwygSurfaceSource).toMatch(/:global\(\.aimd-recorder-dropcursor/)
    expect(wysiwygSurfaceSource).toMatch(/\.aimd-editor-wysiwyg-mode\) \{\s*position: relative;/)
    expect(wysiwygSurfaceSource).toMatch(/Drop here|拖到这里/)
  })

  it('can disable raw AIMD snippet editing inside the recorder-side field dialog', () => {
    expect(source).toMatch(/allowRawFieldSourceEditing\?: boolean/)
    expect(source).toMatch(/allowRawFieldSourceEditing: true/)
    expect(source).toMatch(/if \(!props\.allowRawFieldSourceEditing \|\| !activeFieldEditor\.value\)/)
    expect(source).toMatch(/v-if="allowRawFieldSourceEditing"/)
  })

  it('re-exposes manual client assigner controls from the inner recorder', () => {
    expect(source).toMatch(/runClientAssigner: \(id: string\) => recorderRef\.value\?\.runClientAssigner\(id\)/)
    expect(source).toMatch(/runManualClientAssigners: \(\) => recorderRef\.value\?\.runManualClientAssigners\(\)/)
  })

  it('is exported from both the component entry and the root package entry', () => {
    expect(componentExports).toMatch(/AimdRecorderEditor/)
    expect(rootExports).toMatch(/AimdRecorderEditor/)
  })
})
