export {
  AIMD_FIG_ID_PATTERN,
  AimdFormalOutputError,
  collectAimdFigureIds,
  createAimdFigureId,
  normalizeAimdFigureIds,
  prepareAimdForFormalOutput,
  scanAimdFigureBlocks,
  type AimdFigureBlockInfo,
  type AimdFigureSourceField,
  type AimdTextEdit,
  type GeneratedAimdFigureId,
  type NormalizeAimdFigureIdsResult,
  type PrepareAimdFormalOutputResult,
} from './fig'
