export type {
  AimdCheckRecordItem,
  AimdDnaSequenceAnnotation,
  AimdDnaSequenceQualifier,
  AimdDnaSequenceSegment,
  AimdDnaSequenceValue,
  AimdProtocolRecordData,
  AimdStepRecordItem,
  AimdStepOrCheckRecordItem,
} from '../types'
export { createEmptyProtocolRecordData } from '../types'
export type {
  AimdRecorderValidationCode,
  AimdRecorderValidationTrigger,
  AimdRecordValidationSchema,
  AimdRecorderValidationIssue,
  AimdRecorderValidationResult,
} from '../types'
export {
  getAimdRequiredFieldKeys,
  getAimdVarTableCellFieldKey,
  matchesAimdValidationFieldSelector,
  validateAimdField,
  validateAimdRecord,
  type ResolveAimdRequiredFieldOptions,
  type ValidateAimdRecordOptions,
} from './validation'

export {
  applyIncomingRecord,
  applyNormalizedRecord,
  applyPastedVarTableGrid,
  cloneRecordData,
  createEmptyVarTableRow,
  ensureDefaultsFromFields,
  getQuizDefaultValue,
  getRecordDataSignature,
  normalizeCheckFields,
  normalizeCheckLike,
  normalizeIncomingRecord,
  normalizeQuizFields,
  normalizeStepFields,
  normalizeStepLike,
  normalizeVarTableFields,
  normalizeVarTableRows,
  parsePastedVarTableText,
  replaceSection,
  type ApplyVarTablePasteResult,
  type VarTablePastedCell,
} from '../composables/useRecordState'

export {
  createEmptyCheckRecordItem,
  createEmptyStepRecordItem,
  formatStepDuration,
  getProtocolEstimatedDurationMs,
  getProtocolRecordedDurationMs,
  getStepElapsedMs,
  getStepRemainingMs,
  hasRecordedStepDuration,
  isStepTimerRunning,
  isStepTimerWarning,
  normalizeStepTimerState,
  pauseStepTimer,
  resetStepTimer,
  resolveStepTimerMode,
  setStepChecked,
  startStepTimer,
} from '../composables/useStepTimers'

export {
  AIMD_DNA_SEQUENCE_FORMAT,
  calculateDnaSequenceGcPercent,
  collectInvalidDnaSequenceCharacters,
  createEmptyDnaSequenceAnnotation,
  createEmptyDnaSequenceQualifier,
  createEmptyDnaSequenceSegment,
  getDnaSequenceSegmentIssue,
  getNextDnaSequenceAnnotationId,
  normalizeDnaSequenceAnnotation,
  normalizeDnaSequenceName,
  normalizeDnaSequenceQualifier,
  normalizeDnaSequenceSegment,
  normalizeDnaSequenceText,
  normalizeDnaSequenceValue,
  serializeDnaSequenceToGenBank,
} from '../composables/useDnaSequence'

export {
  AIMD_AIRALOGY_FILE_ID_RE,
  AIMD_FILE_BADGE_BY_KIND,
  AIMD_FILE_ID_VALUE_KEYS,
  AIMD_FILE_INPUT_CONFIG_BY_TYPE,
  AIMD_FILE_KIND_BY_EXTENSION,
  AIMD_FILE_REFERENCE_VALUE_KEYS,
  AIMD_MIME_BY_EXTENSION,
  AIMD_RECORD_DATA_SCOPES,
  getAimdAcceptFromExtension,
  getAimdAssetMediaSource,
  getAimdConfiguredFileExtension,
  getAimdDisplayValue,
  getAimdFileDisplayName,
  getAimdFileExtension,
  getAimdFileExtensionFromTypeName,
  getAimdFileInputConfig,
  getAimdFileKindFromExtension,
  getAimdFileKindFromMimeType,
  getAimdFileKindFromType,
  getAimdFileValueId,
  getAimdStringFromRecord,
  inferAimdAssetKind,
  isAimdAiralogyFileId,
  isAimdBooleanType,
  isAimdCodeType,
  isAimdDnaType,
  isAimdEmbeddableAssetUrl,
  isAimdFileLikeType,
  isAimdMarkdownType,
  isAimdPlainRecord,
  isKnownAimdFileTypeName,
  normalizeAimdFileExtension,
  normalizeAimdOptionalTypeName,
  normalizeAimdRecordDataValue,
  normalizeAimdString,
  normalizeAimdTypeName,
  resolveAimdRecordData,
  stringifyAimdDisplayValue,
  toAimdBooleanValue,
  unwrapAimdStructuredValue,
  type AimdAssetKind,
  type AimdAssetLike,
  type AimdFileInputConfig,
  type AimdFileInputMetadata,
  type AimdRecordDataScope,
  type AimdRecordDataValue,
} from '@airalogy/aimd-core/utils'
