import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const source = readFileSync(resolve(__dirname, './EditorDemo.vue'), 'utf8')

describe('EditorDemo archive export', () => {
  it('starts as a blank online editor and loads examples only as templates', () => {
    expect(source).toContain("content.value = ''")
    expect(source).toContain('activeTemplateExampleId')
    expect(source).toContain('activeTemplateLocale')
    expect(source).toContain('canClearContent')
    expect(source).toContain('clearEditorContent')
    expect(source).toContain('contentCleared')
    expect(source).toContain('handleExampleTemplateSelect')
    expect(source).toContain('loadSelectedExampleTemplate')
    expect(source).toContain('templatePickerTitle')
    expect(source).toContain('blankTemplateHint')
    expect(source).toContain('emptyPreview')
    expect(source).toContain('resolveDemoExampleAsset')
    expect(source).toContain('getDemoExample(activeTemplateExampleId.value)')
    expect(source).not.toContain('pages.editor.desc')
    expect(source).not.toContain("watch(locale, () => {\n  clearProtocolFiles()\n  resetToSelectedExample(locale.value)\n})")
  })

  it('packages uploaded images as protocol-local figure files', () => {
    expect(source).toContain('createProtocolAiraArchive')
    expect(source).toContain('```fig')
    expect(source).toContain('src: ${toAimdScalar(figure.src)}')
    expect(source).toContain('insertProtocolFigureBlock(figureFile, metadata)')
    expect(source).toContain('makeResourceBaseName(getFileStem(file.name), `uploaded-figure-${index}`)')
    expect(source).toContain('replace(/[^\\p{L}\\p{N}._-]+/gu, \'-\')')
    expect(source).toContain('files/${baseName}.${extension}')
    expect(source).not.toContain('airalogy.id.file')
  })

  it('uses the editor image toolbar as the figure insertion entrypoint', () => {
    expect(source).toContain('image-toolbar-action="custom"')
    expect(source).toContain('@request-image="openImageInsertPanel"')
    expect(source).toContain('<Teleport to="body">')
    expect(source).toContain('class="figure-insert-popover"')
    expect(source).toContain('buttonRect')
    expect(source).toContain('figureInsertSource')
    expect(source).toContain('localFigureMode')
    expect(source).toContain('remoteFigureMode')
    expect(source).toContain('insertRemoteFigure')
    expect(source).toContain('openFigureFilePicker')
  })

  it('downloads plain AIMD until protocol-local files require an archive', () => {
    expect(source).toContain('protocolFileCount.value === 0')
    expect(source).toContain('`${filenameStem}.aimd`')
    expect(source).toContain('`${filenameStem}.aira`')
    expect(source).toContain('workspace-panel__actions')
    expect(source).toContain('workspace-panel__download')
    expect(source).not.toContain('archive-toolbar')
  })

  it('imports plain zip or .aira packages into the online editor before repacking', () => {
    expect(source).toContain('openAiraArchive')
    expect(source).toContain('openZipArchive')
    expect(source).toContain('readAiraPackage')
    expect(source).toContain('readAiraProtocolPackage')
    expect(source).toContain('readAiraRecordsPackage')
    expect(source).toContain('readZipFolderPackage')
    expect(source).toContain('chooseZipAimdEntrypoint')
    expect(source).toContain('protocol.aimd')
    expect(source).toContain('index.aimd')
    expect(source).toContain('packageInputRef')
    expect(source).toContain('accept=".zip,.aira,application/zip,application/vnd.airalogy.archive+zip"')
    expect(source).toContain('handlePackageFileSelected')
    expect(source).toContain('openPackageFilePicker')
    expect(source).toContain('applyImportedPackage')
    expect(source).toContain('applyImportedProtocolPackage')
    expect(source).toContain('packageImportNoAimd')
    expect(source).toContain('packageImportNoRecords')
    expect(source).toContain('createImportedProtocolFile')
    expect(source).toContain('createImportedProtocolFiles')
    expect(source).toContain("const protocolFilesExpanded = ref(false)")
    expect(source).toContain('protocolFilesExpanded.value = false')
    expect(source).toContain('importPackageHint')
    expect(source).toContain('workspace-panel__import-tooltip')
    expect(source).toContain('aria-describedby="editor-import-package-tooltip"')
    expect(source).toContain('white-space: pre-wrap;')
  })

  it('imports records .aira packages by loading the embedded protocol and selected record data', () => {
    expect(source).toContain('importedRecordOptions')
    expect(source).toContain('selectedImportedRecordId')
    expect(source).toContain('importedRecordFilterQuery')
    expect(source).toContain('filteredImportedRecordOptions')
    expect(source).toContain('archiveStatusDisplayLabel')
    expect(source).toContain(':title="archiveStatusLabel"')
    expect(source).toContain('collectAimdRecordFieldRefs')
    expect(source).toContain('filterAimdRecords')
    expect(source).toContain('collectAiraProtocolEntries')
    expect(source).toContain('findAiraProtocolForRecord')
    expect(source).toContain('recordPayloadToRecorderData')
    expect(source).toContain('embedded_protocol_root')
    expect(source).toContain('packageImportMissingProtocol')
    expect(source).toContain('applyImportedRecordOption')
    expect(source).toContain('handleImportedRecordSelected')
    expect(source).toContain('workspace-panel__record-select')
    expect(source).toContain('workspace-panel__record-filter')
    expect(source).toContain('workspace-panel__record-filter-toggle')
    expect(source).toContain('showImportedRecordFilterPanel')
    expect(source).toContain('toggleImportedRecordFilter')
    expect(source).toContain('aria-controls="editor-record-filter"')
    expect(source).toContain('importedRecordFilterPlaceholder')
    expect(source).toContain('importedRecordFilterCount')
    expect(source).toContain('importedRecordSelect')
    expect(source).toContain('packageImportedRecordCount')
    expect(source).toContain('showImportedRecordFilter')
    expect(source).toContain('hideImportedRecordFilter')
    expect(source).toContain('protocolKey: protocolEntry.path')
    expect(source).toContain('activeImportedRecordOptions')
    expect(source).toContain('visibleImportedRecordOptions')
    expect(source).toContain('selectedImportedRecords')
    expect(source).toMatch(/\.workspace-panel__title \{[\s\S]*?white-space: nowrap;/)
    expect(source).toMatch(/\.workspace-panel__actions \{[\s\S]*?flex: 1 1 auto;[\s\S]*?min-width: 0;/)
    expect(source).not.toContain('v-if="previewMode === \'recorder\' && importedRecordCount > 1"')
    expect(source).toMatch(/\.workspace-panel__record-filter \{[\s\S]*?display: grid;[\s\S]*?border-bottom: 1px solid #e5edf6;/)
    expect(source).toContain("previewMode.value = 'recorder'")
  })

  it('opens imported Record collections in shared table and comparison views', () => {
    expect(source).toContain('AimdRecordTable')
    expect(source).toContain('AimdRecordCompare')
    expect(source).toContain("type PreviewMode = 'render' | 'recorder' | 'records-table' | 'records-compare'")
    expect(source).toContain("previewMode.value = sameProtocolRecordCount > 1 ? 'records-table' : 'recorder'")
    expect(source).toContain('v-model:selected-record-keys="selectedImportedRecordKeys"')
    expect(source).toContain('v-model:field-keys="importedRecordFieldKeys"')
    expect(source).toContain('v-model:show-only-differences="showOnlyImportedRecordDifferences"')
    expect(source).toContain("previewMode.value === 'records-table' || previewMode.value === 'records-compare'")
    expect(source).toContain(':records="visibleImportedRecordOptions"')
    expect(source).toContain(':records="selectedImportedRecords"')
    expect(source).toContain(':selection-limit="4"')
    expect(source).toContain('@open-record="openImportedRecord"')
    expect(source).toContain('recordTableMode')
    expect(source).toContain('recordCompareMode')
    expect(source).toMatch(/\.record-collection-preview \{[\s\S]*?background: #f8fafc;/)
  })

  it('keeps imported protocol file lists collapsed and scrollable', () => {
    expect(source).toContain('protocolFileTotalSize')
    expect(source).toContain('workspace-panel__file-summary')
    expect(source).toContain('class="archive-button workspace-panel__file-toggle"')
    expect(source).toContain(':aria-expanded="protocolFilesExpanded"')
    expect(source).toContain('v-if="protocolFileCount > 0 && protocolFilesExpanded"')
    expect(source).toContain('messages.pages.editor.showFiles')
    expect(source).toContain('messages.pages.editor.hideFiles')
    expect(source).toMatch(/\.workspace-panel__file-toggle \{[\s\S]*?background: #eff6ff;[\s\S]*?color: #1d4ed8;/)
    expect(source).toMatch(/\.protocol-file-list \{[\s\S]*?max-height: min\(360px, 46vh\);[\s\S]*?overflow-y: auto;/)
  })

  it('autosaves and restores local editor drafts with protocol files', () => {
    expect(source).toContain('EDITOR_DRAFT_DB_NAME')
    expect(source).toContain('indexedDB.open')
    expect(source).toContain('StoredProtocolFigureFile')
    expect(source).toContain('blob: file.file')
    expect(source).toContain('new File([file.blob], file.name')
    expect(source).toContain('restoreEditorDraft')
    expect(source).toContain('scheduleEditorDraftSave')
    expect(source).toContain('saveEditorDraftNow')
    expect(source).toContain('clearEditorDraft')
    expect(source).toContain("window.addEventListener('pagehide', handleEditorPageHide)")
    expect(source).toContain('void restoreEditorDraft()')
    expect(source).toContain('void clearEditorDraft().catch(handleEditorDraftError)')
    expect(source).toContain('draftRestored')
    expect(source).toContain('draftSaveFailed')
  })

  it('lets the right panel switch between static render preview and a fillable recorder form', () => {
    expect(source).toContain('AimdRecorder')
    expect(source).toContain('createEmptyProtocolRecordData')
    expect(source).toContain("type PreviewMode = 'render' | 'recorder' | 'records-table' | 'records-compare'")
    expect(source).toContain("const previewMode = ref<PreviewMode>('render')")
    expect(source).toContain('previewPanelTitle')
    expect(source).toContain('preview-mode-tabs')
    expect(source).toContain("previewMode = 'render'")
    expect(source).toContain("previewMode = 'recorder'")
    expect(source).toContain('v-model="recorderData"')
    expect(source).toContain(':resolve-file="resolveRecorderFile"')
    expect(source).toContain('resetRecorderData')
    expect(source).toContain('recorderMode')
    expect(source).toContain('emptyRecorder')
  })

  it('keeps the live preview from adding a panel-level horizontal scrollbar', () => {
    expect(source).toMatch(/\.workspace-panel__body \{[\s\S]*?overflow-x: hidden;/)
    expect(source).toMatch(/\.workspace-panel__body \{[\s\S]*?overflow-y: auto;/)
    expect(source).toMatch(/\.render-preview \{[\s\S]*?overflow-wrap: anywhere;/)
    expect(source).toMatch(/\.render-preview \{[\s\S]*?padding: 0 20px 20px;/)
    expect(source).toMatch(/\.render-preview::before \{[\s\S]*?height: 20px;/)
    expect(source).toMatch(/\.recorder-preview \{[\s\S]*?padding: 0;/)
    expect(source).toMatch(/\.recorder-preview :deep\(\.aimd-protocol-recorder\) \{[\s\S]*?--aimd-recorder-gutter-x: 14px;[\s\S]*?--aimd-recorder-gutter-bottom: 14px;/)
    expect(source).toMatch(/\.render-preview :deep\(table:not\(\.aimd-field__table-preview\)\) \{[\s\S]*?overflow-x: auto;/)
    expect(source).toMatch(/\.render-preview :deep\(\.aimd-field__table-preview\) \{[\s\S]*?display: table;/)
    expect(source).toMatch(/\.render-preview :deep\(pre\) \{[\s\S]*?overflow-x: auto;/)
  })

  it('uses the renderer typography container for live preview prose', () => {
    expect(source).toContain('class="workspace-panel__body render-preview aimd-renderer"')
    expect(source).not.toMatch(/\.render-preview :deep\(h1\)/)
    expect(source).not.toMatch(/\.render-preview :deep\(ul\) \{[\s\S]*?list-style: disc outside;/)
  })
})
